### ISSUE TITLE
Track arming with bottom track buttons breaks if "record to arrangement" is on

### ISSUE THREAD

**Issue by mwozniczak** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#22] opened 2022-06-25 06:47 UTC
Finally I've managed to find a way to make this bug reproducible (I think), here are the steps

1. turn this button on: ![image](https://user-images.githubusercontent.com/14187903/175761653-e6077849-ac63-4745-8bab-b99e397a6c90.png)
2. have two instrument tracks (or more, but 2 should be enough for the test): e.g. one drum, one synth, don't know if the type is relevant but one being a drum machine and one not helps to see whether the instrument-specific layout changed
3. record something to the first one, either via shift+record, or by tapping the empty clip in session view and being fast enough
4. confirm the recording by pressing the record button again
5. switch to the second instrument by pressing the button above the "mute/redo"

expected behavior: you switch to the second instrument's layout, the second track is armed and you can play it
actual behavior: the layout changes (usually), but the track is not armed, so if you want to play a synth, you get a faceful of kick instead

if i disable the record to arrangement button, everything seems to work as expected

**Comment by mwozniczak** [comment] 2022-06-27 10:51
@weskoop i could try fixing it myself, but since i'm still fairly fresh to the codebase, can you point me to where this might be located?

**Comment by weskoop** [comment] 2022-07-03 02:37
Finally had a bit of time to try this (I'm on 4.3). But I'm not really clear on the issue. I had no problems jumping between 2 armed tracks and recording clips. Either With "Write Arranger Automation/Arranger Record on or off". Both tracks seems to behave as expected depending on if they are armed or not. Maybe I need some clarity on the issue.

**Comment by mwozniczak** [comment] 2022-07-03 13:54
@weskoop okay i figured this is one of the cases where showing is better than telling, so here's me demonstrating the bug in an awkward minute and a half: https://www.youtube.com/watch?v=qxMJ8hUiz8g

hope this helps!

**Comment by weskoop** [comment] 2022-07-03 19:52
Thanks for the clear video. I use Bitwig with "Auto Arm" disabled, which is why I do not see any issues.

With that said, this seems to be a bug in Bitwig itself, you can recreate this behaviour just inside the bitwig UI, without the launchpad. When you click a Track button, all it's doing is a `selectInMixer()` call here:

https://github.com/weskoop/Launchpad-Pro-Mk3-for-Bitwig/blob/797ff2bd8903731ec8667e9fa9bd8e3948d57fb5/src/Layers/Session.ts#L235

This is the same as clicking with a mouse to select a track. The Bitwig preferences will determine what to do with it at this point. 

The bug/issue is that when the Transport is running AND Arranger record is enabled, the Auto-Arm feature does not work when selecting a track. I doubt this is by design, but there may be a reason, you should submit the bug to Bitwig, see if they can sort it out.

**Comment by weskoop** [comment] 2022-07-03 19:53
Going to close this issue, since it's unrelated to the script. Thanks for taking the time @mwozniczak, hopefully Bitwig proper can sort it out for you.

**Closed by weskoop** 2022-07-03 19:53 UTC
Labels: bug, wontfix

**Comment by mwozniczak** [comment] 2022-07-03 20:09
@weskoop hey, one thing i noticed when trying to replicate this in the UI, that might still be relevant: i _think_ when I finalize recording a clip (i.e. press the record button the second time), this is where things break. How are you handling that functionality, because either I'm not replicating it quite right in the UI, orrrrr maybe we're on to something after all? ;)

**Comment by mwozniczak** [comment] 2022-07-03 20:21
okay scratch that, when I enabled "start transport on record" to see if that was it, the auto-arming stopped working. So I guess that confirms it, this seems to be a bitwig bug, sorry to have wasted your time, and thanks for looking into it!

**Comment by weskoop** [comment] 2022-07-03 21:20
No worries! Thanks for the interest, enjoy the script!

**Comment by mwozniczak** [comment] 2022-07-04 11:42
Hey, just to wrap this one up, you were right! Here's the official reply from bitwig's support:

> yes, the auto arming is being paused while recording, currently this can't be change but thanks for your suggestion!

Super frustrating, but I guess, glad we sorted this one out!
