### ISSUE TITLE
💡 Idea: Use of colors in some layers

### ISSUE THREAD

**Issue by Fannon** [weskoop/Launchpad-Pro-Mk3-for-Bitwig#5] opened 2022-01-21 18:41 UTC
Hi,

just an idea / minor suggestion to throw into the room. Feel free to ignore / disagree.

When switching into different layers than Session, the track buttons get all the same color as the functionality chosen. 
If they keep the color of the tracks, there is a bit more context. What track is then enabled / active could also be indicated by keeping the same color but making it pulsing. When choosing Volume, Pan or Sends it the track color could also be used as a fader color?

For the Device page, I wonder if it is possible to use the colors from the bitwig device remote controls?
To me it looks like it's always the same 8 colors in the same order. Here both track colors and fader colors could be adjusted.

**Comment by weskoop** [comment] 2022-01-22 01:37
**Faders**
I actually did most of the development with Coloured Volume and Pan Faders. It really starts to break down on the Launchpad as the Clip Launcher fills up, then (especially in Arrange View) the sliders, just start to look like rows of clips.

 Its way more orienting to change the colour of the Pads to represent what the Launchpad is going to do. Is also as intended by Novation, and I think for good reason.

I might feel different about Sends and Devices... would need to think about it. With Sends, would do do the track Colour? or the Return track colour? Devices, would just be a rainbow, but it's pretty easy to orient yourself in that the first 4 faders are the top knobs, and last 4 faders are the bottom, i think the rainbow (sadly) would be distracting, and also add to the confusion i mentioned above with the clip launcher.

 With any of them, i would only do it with a preference option to toggle each fader type's colour behaviour on and off. 

**Track Select Buttons** 
The function of these buttons changes when on a fader page, they will reset the corresponding fader. If we change these to represent track selection, then I would return to multi colour. It was a deviation from the normal behaviour I considered worth it, since all of the other track mode overlays provide a different function on the Track select buttons, it felt weird that the fader modes would keep track select buttons.

You can use the Momentary holds on volume or pan buttons, to orient your track colours.

If you want to try it with Volume and Pan, you can add this...
```
// Set Fader Colours (Volume and Pan)
ext.midiDawOut.sendMidi(181, trackIdx, colour.idx);
ext.midiDawOut.sendMidi(181, trackIdx + 0x10, colour.idx);
```
to here...
https://github.com/weskoop/Launchpad-Pro-Mk3-for-Bitwig/blob/2570d3d41eb902782c370197d4a1d452d8568bcd/src/LaunchPad.ts#L378

**Comment by Fannon** [comment] 2022-01-22 08:26
Thanks for the reply! 
Ok, I can see your points and maybe this idea was just good in theory and not so much in practice when you try it out. 
I can see that making the faders to colorful could actually be less helpful than thought.
And that the track buttons color should align to the functionality of those. If they're used for track switching, they should have the color of the tracks. If they control the faders it makes sense that they have the same color as the fader it controls.

> The function of these buttons changes when on a fader page, they will reset the corresponding fader. If we change these to represent track selection, then I would return to multi color. 

I've also thought about this. My first reaction was that it would be useful to use them as track select buttons, but then I saw that using them to reset the faders is also very useful. Maybe it depends on your situation what is more useful. Having better control over the faders or being able to quickly jump between tracks. The layout where I would have found a track select most useful was the device view.

> You can use the Momentary holds on volume or pan buttons, to orient your track colors.

That's a good point / tip!

**Comment by weskoop** [comment] 2022-01-22 16:34
I will close this for now, we can reopen if needed.

**Comment by Fannon** [comment] 2022-01-23 06:33
Yes, for now you have a good point why it is the way it is. 
Maybe if I get to it I'll play around and if something feels right, I could create a PR and we discuss on that concretely.

**Comment by weskoop** [comment] 2022-02-04 18:25
Now that it's 1.0 and "done", I keep thinking about this one, and I keep thinking about making some more "fun" options, In general I find Bitwig more Fun/Playful/inviting than Ableton.

 I wonder if we should do a single `Rainbow Faders` Toggle:
- Colour all the Faders with Track Colours
- Colour the Device Faders to match the Remote Control Colours
- Colour the Sends with the Effects Tracks Colours

We should leave the "Track Select/Fader Reset buttons" to reflect the Layer colours, hopefully this is enough to ground the UI and visualize that you are in "Volume" or "Sends", etc.

**Comment by weskoop** [comment] 2022-02-20 01:09
Added to main branch.

**Closed** 2022-02-20 01:14 UTC
Labels: enhancement
